### PR TITLE
fix: Allow cancelling updates in manage page

### LINKED ISSUE #1533: manage: users can't cancel updates
Screenshot 2023-12-13 at 16 58 30

currently, the users can't cancel the updates after clicking on [update all]. we should offer that option.

screenshots (also on figma)
Screenshot 2023-12-13 at 16 58 55

### PR DESCRIPTION
**Pull request by codinesh**
Fixes #1533 by adding a Cancel button next to 'Update All' in manage page.

Cancel button is disabled by default, when no updates are not initialized.
image

Once update all is triggered and in progress, Cancel button will be enabled, and will stop the updates on click.
image

Hello @anasereijo, I couldn't find the link to Figma, to make the button width match with designs. Will be happy to take that change, please help me with Figma link and access.

### CODE REVIEW

**Comment by codinesh** [comment]
Hello @BLKKKBVSIK, can you please review this as well, when you get chance. Thanks.

**Comment by codinesh** [comment]
@spydon, @BLKKKBVSIK please review this when you get time..

File: packages/app_center/lib/src/manage/manage_page.dart [hunk 1]
```diff
@@ -304,6 +304,21 @@ class _ActionButtons extends ConsumerWidget {
                   ],
                 ),
         ),
+        const SizedBox(width: 8),
+        PushButton.outlined(
+          onPressed: updatesModel.refreshableSnapNames.isNotEmpty &&
+                  !updatesModel.state.isLoading &&
+                  updatesModel.activeChangeId != null
```
Comment (spydon) [inline packages/app_center/lib/src/manage/manage_page.dart:311]: I would move this out to a variable with a good name so that the code gets more readability

File: packages/app_center/lib/src/snapd/updates_model.dart [hunk 2]
```diff
@@ -63,4 +63,25 @@ class UpdatesModel extends ChangeNotifier {
...
   }
+
+  Future<void> cancelChange(String changeId) async {
+    if (changeId.isEmpty) return;
+
+    try {
+      final changeDetails = await snapd.getChange(changeId);
+
+      // If the change is already completed, ignore silently.
+      // Otherwise an erorr will be displayed to user, which might be confusing.
```
Comment (spydon) [inline packages/app_center/lib/src/snapd/updates_model.dart:74]:
```suggestion
      // If it wouldn't be ignored, an error would be displayed to the user,
      // which might be confusing.
```

**Review by spydon — COMMENTED** [review]
Not sure why the mocks are failing, can you try running `melos generate`?

File: packages/app_center/lib/src/manage/manage_page.dart (hunk 1 above)
Comment (codinesh) [reply packages/app_center/lib/src/manage/manage_page.dart]: Thanks for suggestion, made the change to extract a variable.

Ran `melos generate`, and it fixed the missing mock definition. Thanks.

**Comment by BLKKKBVSIK** [comment]
Few tests aren't passing, once this will be resolved, LGTM

**Comment by codinesh** [comment]
> Few tests aren't passing, once this will be resolved, LGTM

@BLKKKBVSIK, thanks for review, fixed the tests now. Please have a look when you get chance.

**Review by spydon — APPROVED** [review]
Lgtm!

**Comment by codinesh** [comment]
> Lgtm!

thanks for review @spydon. 

@BLKKKBVSIK please let me know if there is any thing I can do for this PR to be merged..

**Comment by anasereijo** [comment]
Hey @codinesh thanks for working on this 🙌

One thing to amend is that the cancel button should be hidden until the 'Update all' is trigged, as it can be misleading for the users to have a cancel button without context.

>Hello @anasereijo, I couldn't find the link to Figma, to make the button width match with designs. 

The width of the button is dependent on the text length, with a padding of 16px on both sides. Not 100% if this is what we have on Yaru, so please double-check.

Cheers!

**Comment by codinesh** [comment]
> One thing to amend is that the cancel button should be hidden until the 'Update all' is trigged, as it can be misleading for the users to have a cancel button without context.

Hello @anasereijo, Thanks for suggestions, I will take up the change to hide Cancel button while not processing updates.
