### PR TITLE
fix(manage): update all button

### LINKED ISSUE #1406: 'Update all' button remains enabled during update (manage page)
It also doesn't correctly display the "Updating" state.

### PR DESCRIPTION
**Pull request by d-loose**
UDENG-1487
Fixes #1406, #1414
Also prevents division by zero in the progress calculation

### CODE REVIEW

File: test/snap_model_test.dart [hunk 1]
```diff
@@ -232,4 +232,30 @@ void main() {
     );
     await model.install();
   });
+  group('change progress', () {
```
Comment (d-loose) [inline test/snap_model_test.dart:235]: I'm experimenting with golang-style table driven unit tests here. Unlike Flutter's `testWidgets()`, Dart's `test()` doesn't offer [variants](https://api.flutter.dev/flutter/flutter_test/TestVariant-class.html). Calling `test()` in a loop like this works fine, but might confuse the editor/IDE.

**Review by tim-hm — APPROVED** [review]
I've struggled to test the update button locally, but looking through the code it looks good to me!
