### PR TITLE
fix: sidebar navigation highlight

### LINKED ISSUE #1379: Sidebar navigation not highlighted when clicking section on explore page
## issue

1. Activate explore page
2. Scroll down to a banner (ie "Featured Snaps" or "Must have snaps for developers")
3. Click "Discover more"
4. The correct page is activated but it has a back button and the left side navigation isn't selected.

image

## expected behaviour

When activating a 'top level' section, I would expect the left nav bar to reflect the active page.

### PR DESCRIPTION
**Pull request by BLKKKBVSIK**
In this PR:

- Open the correct section when clicking on a banner button from the explore page.

fix #1379

### CODE REVIEW

File: packages/app_center/lib/src/store/store_pages.dart [hunk 1]
```diff
@@ -8,6 +8,13 @@ import 'package:flutter/material.dart';
 import 'package:flutter_riverpod/flutter_riverpod.dart';
 import 'package:yaru_widgets/yaru_widgets.dart';
 
+final displayedCategories = [
+  SnapCategoryEnum.featured,
+  SnapCategoryEnum.productivity,
+  SnapCategoryEnum.development,
+  SnapCategoryEnum.games,
```
Comment (spydon) [inline packages/app_center/lib/src/store/store_pages.dart:15]: Unrelated to this PR, enums should not have Enum appended to their names

**Review by spydon — APPROVED** [review]

File: packages/app_center/lib/src/store/store_pages.dart (hunk 1 above)
Comment (BLKKKBVSIK) [reply packages/app_center/lib/src/store/store_pages.dart:15]: I'll probably update that in a another PR.
