### PR TITLE
fix: splash on up/down vote fills container

### LINKED ISSUE #1392: Ratings thumbs splash does not fill container
The splash on the thumbs up an thumbs down for up/down voting a snap does not fill the container it sits in, only a circle around the thumb

### PR DESCRIPTION
**Pull request by matthew-hagemann**
Closes #1392 

- I found it difficult to manage the splash filling only half the decorator box the thumbs lived in, so split them into two, one for up vote, one for down, and managed the splash in separate InkWells.
- Updated colors of thumbs and widget border to better align with the rest of the App Center & designs

### CODE REVIEW

**Comment by tim-hm** [comment]
Removed myself as reviewer bc I won't be able to review in a reasonable timeframe

**Comment by d-loose** [comment]
I'll have a look at it after lunch! :slightly_smiling_face: 
@matthew-hagemann could you please rebase and target main?

**Comment by matthew-hagemann** [comment]
> I'll have a look at it after lunch! 🙂 @matthew-hagemann could you please rebase and target main?

I see main is at the same commit my branch was based on (both 1 commit behind current dev branch), so I think all is aligned?

**Comment by d-loose** [comment]
> I see main is at the same commit my branch was based on (both 1 commit behind current dev branch), so I think all is aligned?

Yes, thanks!

File: lib/src/snapd/snap_page.dart [hunk 1]
```diff
@@ -424,37 +424,80 @@ class _RatingsActionButtons extends ConsumerWidget {
...
+                  child: YaruIconButton(
+                    icon: ratingsModel.vote == VoteStatus.up
+                        ? Icon(
+                            Icons.thumb_up,
+                            color: Theme.of(context).iconTheme.color,
+                          )
+                        : Icon(
+                            Icons.thumb_up_outlined,
+                            color: Theme.of(context).iconTheme.color,
+                          ),
```
Comment (d-loose) [inline lib/src/snapd/snap_page.dart:461]: Could be simplified a little by putting the conditional expression into the `Icon()`

File: lib/src/snapd/snap_page.dart [hunk 2]
```diff
@@ -424,37 +424,80 @@ class _RatingsActionButtons extends ConsumerWidget {
...
+                  child: YaruIconButton(
+                    icon: ratingsModel.vote == VoteStatus.down
+                        ? Icon(
+                            Icons.thumb_down,
+                            color: Theme.of(context).iconTheme.color,
+                          )
+                        : Icon(
+                            Icons.thumb_down_outlined,
+                            color: Theme.of(context).iconTheme.color,
+                          ),
```
Comment (d-loose) [inline lib/src/snapd/snap_page.dart:496]: Same as above

**Review by d-loose — APPROVED** [review]
Besides very minor comments - LGTM! :+1:
